### ISSUE TITLE
Items visible prematurely in accessibility mode

### ISSUE THREAD

**Issue by simondate** [danielstorey/adapt-stacklist#1]
If you enable accessibility you can tab across and see items that shouldn't be visible yet.

**Comment by danielstorey** [comment]
Thanks Simon,
TBH I'm quite new to accessibility so thanks for highlighting this. I will provide an update as soon as possible.

**Comment by simondate** [comment]
No worries :) All of these components are really nice. You must have been working on them for a while!

**Comment by danielstorey** [comment]
Thanks mate. I started back in May/June time and have a few more on the way as well! I have provided the update for this component now by setting the items to hidden until immediately before they slide in.
