### ISSUE TITLE
Compatibility with Article Extensions

### ISSUE THREAD

**Issue by joe-replin** [danielstorey/adapt-stacklist#12]
Hello there,

Apologies, but I ran into this issue a month ago and cannot provide a screenshot at this time. When placing the stacklist inside of the article reveal extension, the article reveal will only open as far as the first visible button in the stacklist component. In the meantime, I'm just not using the stacklist inside of any article extensions like article reveal or article block slider. 

I haven't attempted using it inside of an article block slider, but I know from past experience that vertically expanding components like an accordion also will not expand the height of the block slider it is contained within.

Best regards,
Joe Replin

**Comment by danielstorey** [comment]
Hi Joe,

Unfortunately this is due to the way article reveal hides the article. It's very difficult/impossible to measure element dimensions when the parent element is hidden. I might be able to do something about block slider compatibility though...

**Comment by danielstorey** [comment]
Same issue as https://github.com/cgkineo/adapt-article-reveal/issues/13

**Comment by chucklorenz** [comment]
Hi Dan,
I played around with this for a while today, picking up the project that Joe started. Gotta say my skills fell short. I referenced the suggestions in https://github.com/cgkineo/adapt-article-reveal/issues/13 . Couldn't find a way to control the height set in preRender at the time the article reveal is opened. Tried to listen to window.resize but got an error about this.model being undefined. My hack? I set height in the template via JSON. Happy to chat with you if you can help me achieve a proper solution or if I can help define the problem from my recent experiences.

**Comment by danielstorey** [comment]
Hey fellas,

I have updated stacklist so it's worth using the updated version now. I have also submitted somewhat of a fix to article reveal. Until this gets merged you can use my issue-13 branch
https://github.com/danielstorey/adapt-article-reveal/tree/issue-13

**Comment by chucklorenz** [comment]
Hey Dan,
Thanks for the effort with this. I put both fixes in place (stacklist and article-reveal), and the results are successful.

**Comment by danielstorey** [comment]
Great stuff ;)

**Comment by joe-replin** [comment]
Apologies for the fall-off on my part. Thank you both for pushing this forward. I will close this issue.
