### ISSUE TITLE
Would be nice to....

### ISSUE THREAD

**Issue by hbaileylxd** [danielstorey/adapt-stacklist#13]
be able to change from within the AT what the button reads, so instead of Click to Begin you can overwrite that with something of your own choosing, and maybe even the Next button too?

**Comment by danielstorey** [comment]
It should already do that. Do you not have start text and continue text fields under button properties?

**Comment by hbaileylxd** [comment]
ahhhhhhhhhhhhhhhh no I don't, but I do notice you've made changes but no releases, so I wasn't aware there was a later version. I was still on 1.0.1

**Comment by hbaileylxd** [comment]
Well that's me pre-empted by some months! Thanks Dan!

**Comment by danielstorey** [comment]
Hahaha no problem!

**Comment by hbaileylxd** [comment]
This is the problem with not having a "check for updates" button for user uploaded plugins in the Authoring Tool!
