### ISSUE TITLE
When stacklist completes, it doesn't show on navigation progressbar

### ISSUE THREAD

**Issue by samumist** [danielstorey/adapt-stacklist#2]
when the list finishes and the button gone, the navigation progress bar doesn't update its completion status.

**Comment by danielstorey** [comment]
Thanks for feeding this back. I think I was hosting a slightly older version by mistake. It's sorted now and you can check it [here](https://danielstorey.github.io/adapt-demo-course/#/id/co-main)

**Comment by samumist** [comment]
yes, it is indeed sorted:-)
