### ISSUE TITLE
change format of _items array for better authoring tool support

### ISSUE THREAD

**Issue by moloko** [danielstorey/adapt-stacklist#3]
Unfortunately the authoring tool is not great at handling arrays of strings... in fact I think it might not be able to handle them at all. Normally we specify content like this as an array of objects. Appreciate that's going to look a bit clunky when there's only the one property - perhaps an alternative would be to set as a string with a delimiter character e.g. 

``` json
"_items": "This component is useful for making boring text lists that little bit more interactive.|List items slide in from alternating sides.|There is no limit to the number of items you can have.|Although if you have too many it will be a bit boring.|At least now you get the gist of how this works.|That's pretty much it."
```

If you did go down that route it would probably be a good idea to allow the author to specify the delimiter character in the .json

**Comment by danielstorey** [comment]
Hi moloko, thanks for the explanation. I haven't actually used the authoring tool so I'm in the process of making my plugins compatible. At present none of them of the correct properties.schema which is next on my todo list. I have found a workaround for the above though. Putting {{#if this.length}} in the template returns true if the value is a string so we should be able to support arrays of strings in the .json whilst maintaining compatibility in the authoring tool. Update coming soon.

**Comment by danielstorey** [comment]
I've updated the template and also provided a properties.schema file although have not had the chance to test yet

**Comment by simondate** [comment]
I've just tested this component in the Authoring Tool and it's displays the HTML tags instead of rendering them. Not sure if it's tied to this issue.

**Comment by danielstorey** [comment]
Hey Simon,
I take it the component is working in the AT but you were including HTML in your text items which was not being evaluated? Just needed an extra curly brace in the template to ensure handlebars evaluates the HTML rather than render it as text.
Please check again and close this issue if it's working

**Comment by simondate** [comment]
I tried this and it didn't fix it. Surely that would have been an issue for the Framework too?

Not sure if this something to do with a missing attribute in properties.schema however comparing to other components there doesn't seem to be anything missing?

**Comment by danielstorey** [comment]
Have you cleared cache? I noticed sometimes templates.js doesn't update

**Comment by simondate** [comment]
Just tried your version and it works fine. Must have been a cache issue. Thanks very much!
