### ISSUE TITLE
Stacklist reset on revist

### ISSUE THREAD

**Issue by chrisgillison** [danielstorey/adapt-stacklist#5]
Firstly, congratulations on all your components - they're brilliant!

Regarding Stacklist, is there a way to prevent the stacklist from being reset if you run it, then naviagate away from that page, then return - rather like how Trickle behaves?

Regards, Chris

**Comment by danielstorey** [comment]
Hi Chris, thanks a lot for your positive feedback. I need to create this function and allow the user to specify how they want the component to behave via the "_isResetOnRevisit" property. Shouldn't take long so watch this space!

**Comment by danielstorey** [comment]
Done!

**Comment by chrisgillison** [comment]
Perfect! thanks @danielstorey.
